### ISSUE TITLE
Распределение задач

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/Thoughts#1]

**Comment by GeorgijTar** [comment]
Могу взять БД, EF

**Comment by pirozhok1985** [comment]
Взял бы WebApi + Identity(JWT) - Евгений Анисимов

**Comment by nester-a** [comment]
Готов взять Web-API - Нестеров Алексей

**Comment by vitalyKl** [comment]
WPF - Калинин Виталий

**Comment by Demyanov-A** [comment]
Взял бы наверное WPF/EF

**Comment by Oswitto624** [comment]
Могу попробовать в MVC-приложение + дизайн HTML+CSS
Максим Сухарев. В телеге Astrum Zimmerte.

**Comment by Iluzikov** [comment]
Возьму все кроме WPF, готов рискнуть даже с Blazor, имею небольшой опыт написания простых проектов Blazor + Entity EF + Web API + html/css (bootstrap 4/5)

**Comment by Aleksey-Emelyanov** [comment]
БД, WPF

**Comment by natol6** [comment]
А я чайник, поэтому готов на любую работу. Все равно вникать надо во все. Опыт нулевой. Курсы посетил все по специальности разработчик C#. 
Олег Нестеров

**Comment by Chingiz-M** [comment]
Также готов на любую работу, но предпочел бы EF, Web API и в дизайне поковыряться

**Comment by micolla** [comment]
Хочется webAPI или EF, а там посмотрим что выйдет

**Comment by Shiningswords** [comment]
Я тоже чайник. Взял бы что-нибудь из раздела "для неуверенных в себе"))

**Comment by Infarh** [comment]
Все, кто отписался, проверьте статус приглашения

**Comment by Infarh** [comment]
Простые задачи добавлять буду сюда
https://github.com/OpenGeekBrains/Thoughts/labels/Инструменты
Можно разбирать, либо также можно придумывать свои варианты на эту тему.
