### ISSUE TITLE
WebAPI

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/Thoughts#10]
# Создать инфраструктуру хоста WebAPI проекта

## Репозитории 

- [ ] записей блогов
- [ ] разделов
- [ ] тегов
- [ ] авторов
- [ ] комментариев

## Сервисы

- [ ] Блогов (обобщённый сервис, решающий более сложные задачи, чем CRUD интерфейс)

## Клиенты

- [ ] Написать клиентов к создаваемым сервисам, реализующие интерфейсы репозиториев

## Тесты
- [ ] Написать интеграционные тесты

**Comment by pirozhok1985** [comment]
Готов взять в работу - Анисимов Евгений

**Comment by nester-a** [comment]
Ок, всё понятно

**Comment by Infarh** [comment]
Нужно проверить проблемы компиляции кода, возникающие в виду отсутствия класса `Role` #16

**Comment by pirozhok1985** [comment]
> Нужно проверить проблемы компиляции кода, возникающие в виду отсутствия класса `Role` #16

Я взял изменения по сущностям из ветки Георгия https://github.com/OpenGeekBrains/Thoughts/pull/17. Его ещё не заапрувили, поэтому проблема.

**Comment by pirozhok1985** [comment]
Я взял изменения по сущностям из ветки Георгия
https://github.com/OpenGeekBrains/Thoughts/pull/17. Его ещё не заапрувили,
поэтому проблема.

ср, 18 мая 2022 г. в 20:21, Pavel ***@***.***>:
