### ISSUE TITLE
Нужно переделать работу сервиса записей блогов

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/Thoughts#26]
Нужно переделать работу сервиса записей блогов

- Реализовать логику на основе использования репозиториев сущностей
- Исправить методы редактирования категорий и статусов записей

_Originally posted by @Infarh in https://github.com/OpenGeekBrains/Thoughts/issues/24#issuecomment-1143851638_

**Comment by Oswitto624** [comment]
Теперь BlogPostManager умеет работать с репозиториями, и получается да, мой предыдущий сервис для работы с SQL и маппер бесполезны
