### ISSUE TITLE
Создать методы проекции моделей DAL в модели Domain и обратно

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/Thoughts#29]
Настроить карту проекций библиотеки AutoMapper и (или) написать методы-расширения, решающие задачу преобразования типов из моделей предметной области в слой БД

**Comment by Infarh** [comment]
https://www.nuget.org/packages/AutoMapper.Collection.EntityFrameworkCore/8.0.0?_src=template

**Comment by nester-a** [comment]
Берусь

**Comment by Oswitto624** [comment]
В данном пул-реквесте реализованы методы расширения для проекции моделей без Automapper, возможно здесь не будет рекурсий из-за исключения в логике вызова циклических ссылок (т.к. по крайней мере на данный момент нет необходимости в использовании таких проекций - например как раз таки родительские и дочерние комментарии)

**Comment by nester-a** [comment]
> В данном пул-реквесте реализованы методы расширения для проекции моделей без Automapper, возможно здесь не будет рекурсий из-за исключения в логике вызова циклических ссылок (т.к. по крайней мере на данный момент нет необходимости в использовании таких проекций - например как раз таки родительские и дочерние комментарии)

Да, вы правильно нашли места, где у нас появляется рекурсия. Если их исключить, то её не будет))
Лучше уж, конечно, ещё раз подумать нужны ли они нам такие свойства вообще?
