### ISSUE TITLE
Инфраструктура MVVM

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/Thoughts#3]
Требуется создать:

- [x] Реализацию базового класса модели-представления
- [x] Реализацию базового класса команды
- [x] Реализацию модели-представления Главного окна
- [x] Инфраструктуру IoC+DI
- [x] Стили базовых элементов
- [x] Дизайн-макет Главного окна

**Comment by vitalyKl** [comment]
Есть пара вопросов:
1) Как будет осуществляться доступ к админке: конкретным юзерам присваивается роль "admin" и требуется авторизация или все, у кого есть клиент - автоматически являются админами?
2) Есть какой-то перечень функций, которые UI должен уметь отображать и VM должна обрабатывать на основе данных из WebAPI или я проектирую админку, а люди, ответственные за WebAPI и сервисы, должны будут дописать свой код под потребности админки?

**Comment by Infarh** [comment]
Автор-владелец блога должен обладать правами администратора. Но он в настольном клиенте должен всё же авторизоваться на сервисе. Что бы утечка ПО настольного клиента не давало полного доступа к платформе.
Давайте проектировать систему так, что бы иметь возможность в последствии добавлять в неё новые функции.
Начать стоит с операций с записями (создание новой, просмотр имеющихся, редактирование имеющейся и удаление имеющейся записи). И второе направление - файлы на сервере (загрузка, просмотр, удаление с подтверждением). Все операции должны выполняться через профильные сервисы (клиента WebAPI).

**Comment by vitalyKl** [comment]
> 

Т.е. условно наш проект реализует блог только для 1 человека - владельца? Остальные "пользователи" могут только комментировать, я правильно понял?

**Comment by Infarh** [comment]
Да. Начнём с этого. Но сразу заложим, что у каждой записи блога есть автор. Изначально он будет один.
