### ISSUE TITLE
Структура БД

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/Thoughts#4]
Требуется создать слой БД

Он должен быть максимально изолированным от остального приложения. Иметь возможность "жить своей жизнью" при необходимости. Максимум на что он должен полагаться - Базовые Интерфейсы.

Требуется обеспечить хранение следующих сущностей

- [ ] Запись блога
- [ ] ~Автор~ Пользователь
- [ ] Комментарий
- [ ] Раздел (категорию)
- [ ] Тег (ключевое слово)

Запись блога должна иметь
- Дату
- Заголовок
- Текст (тело)
- Автора (название должно быть "Автор", тип - Пользователь (User))
- Категорию
- Список тегов
- Список комментариев
- Статус (черновик, чистовик)
- Признак (bool) удалённой записи - записи из БД удаляются при чистке

~Автор~ Пользователь должен иметь
- ФИО
- Дату рождения
- Список записей блогов
- Список комментариев

Комментарий должен иметь
- Дату
- Автора (тип Пользователь)
- Запись блога, к которой он добавлен
- Родительский комментарий
- Текст
- Список дочерних комментариев
- Признак (bool) удалённой записи - записи из БД удаляются при чистке

Раздел (категория) должен иметь
- Название
- Список записей блогов

Тег должен иметь
- Название
- Список записей блогов к которым он прикреплён

При удалении раздела должно происходить каскадное удаление всех записей
При удалении тега - тег должен удаляться из всех записей, а сами записи должны оставаться

**Comment by GeorgijTar** [comment]
Я бы еще добавил в запись статус (черновик, опубликована и т.д.)

**Comment by Infarh** [comment]
Также добавил требование о необходимости "неудаления" записей из БД. При удалении записи выставляется флаг о том, что она удалена. Сервисы, которые извлекают данные из БД должны обращать внимание на этот флаг и не извлекать "удалённые записи".

**Comment by vitalyKl** [comment]
Прошу прощения, что не в свою задачу лезу, просто хотел предложить сделать сущность не Автора, а пользователя.
Таким образом сможем к каждому конкретному пользователю выставлять конкретную роль: администратор, модератор, автор.
Как мне кажется, это добавит гибкости.

**Comment by Infarh** [comment]
> Прошу прощения, что не в свою задачу лезу, просто хотел предложить сделать сущность не Автора, а пользователя. Таким образом сможем к каждому конкретному пользователю выставлять конкретную роль: администратор, модератор, автор. Как мне кажется, это добавит гибкости.

В какой-то мере поддержу. Внёс исправления.
