### ISSUE TITLE
Создать представление записей блогов в MVC-проекте

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/Thoughts#43]
## Общие требования

- [x] Отображение ленты записей на главной странице
- [x] Детальная информация о выбранной записи
- [x] Доработка в части отображения html-разметки

### Лента записей

Нужно отображение 5-7 записей (число должно браться из конфигурации, или параметра маршрута)
Каждая запись должна иметь:
- Заголовок `Domain.Post.Title`
- Дата `Date`
- Автор `User.NickName`
- Сокращённый текст тела `Body` (Требуется корректный алгоритм обрезки текста - так, что бы не на "полуслове" обрывался текст).

### Детальная информация по выбранной записи

- Заголовок `Domain.Post.Title`
- Дата `Date`
- Автор `User.NickName`
- Категория
- Полный текст с форматированием Html
- Список тегов
- Комментарии

**Comment by kanadeiar** [comment]
Нужна доработка - отображение html-разметки, а не текста, также доработать алгоритм обрезки текста (чтоб корректно отбирал и обрезал html-разметку)
