### ISSUE TITLE
Разработать tag-helper как альтернатива `@Html.Raw(...)`

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/Thoughts#49]
По образу из https://stackoverflow.com/questions/47170660/creating-htmlhelper-raw-tag-helper

**Comment by Infarh** [comment]
Заставить работать вместо

```html
<p>@Html.Raw(Model.Post.Body)</p>
```

сделать примерно так

```html
<p thoughts-raw-html="true">Model.Post.Body</p>
```

**Comment by kanadeiar** [comment]
Создан таг-хелпер с названием "rawhtml"
