### ISSUE TITLE
Создать интерфейс в MVC-проекте для загрузки файлов

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/Thoughts#76]
Создать HTML-форму, обеспечивающую возможность отправки файлов на сервер.
Также нужна страница с отображением списка файлов и возможностью:
- Посмотреть детали файла (имя, длину...)
- Удалить файл с подтверждением этой операции. Удаляемый файл должен быть в БД помечен как удалённый, но физически должен остаться и в БД и на диске.
- При выгрузке файлов списком, либо при запросе файла от сервера на скачивание, сервер должен выдавать 404 ошибку если файл помечен как удалённый.

**Comment by danatoz** [comment]
Платные файловые менеджеры:

https://ru.webix.com/filemanager/
https://ckeditor.com/ckbox/demo/#ckbox
https://demos.devexpress.com/ASPNetCore/Demo/FileManager/Overview/

**Comment by Infarh** [comment]
Загрузка, скачивание и отображение списка работают.
