### ISSUE TITLE
Доменная модель (предметная область)

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/Thoughts#8]
Требуется создать описание "предметной области"

- [x] Запись блога
- [x] Автор
- [x] Раздел
- [x] Тег
- [x] Комментарий

**Comment by nester-a** [comment]
давайте это тоже возьму

**Comment by nester-a** [comment]
Сделал основные сущности.
Решил, чтобы без косяков с веткой дев было, оформить пул на свой личный репозиторий... теперь хз как сюда вытянуть его
Вот ссылка
https://github.com/nester-a/Thoughts/pull/1

**Comment by nester-a** [comment]
Разобрался, как сделать пул в этот проект)))
